### ISSUE TITLE
Is this real-time for `medium` and `large` models?

### ISSUE THREAD

**Issue by jayavanth** [tobiashuttinger/openai-whisper-realtime#1]
Trying to get whisper running on M1 Mac so I can't test it right now. Is it still real-time on medium and large models?

**Comment by tobiashuttinger** [comment]
That entirely depends on how fast your hardware can do the inference. 
On an M1 (Max) the base model _might_ run well. Everything above is still too computationally expensive.

**Comment by jayavanth** [comment]
Thanks! I got it running on M1 Max and looks like it's not fast enough. It's predicting but with a delay. Also I don't think it's using the GPU because % usage is 0. Pretty impressive though that with just CPU I can see it working
